const data = [
    {
      id: 1,
      img: "https://valorantskins.com/img/skins/vandal/aristocrat-vandal-skin.png",
      nameItem: "Vandal Aristocrata",
      value: 100,
      addCart: "Adicionar ao carrinho",
      tag: ["Valorant"],
    },
    {
        id: 2,
        img: "https://valorantskins.com/img/skins/vandal/reaver-vandal-skin.png",
        nameItem: "Vandal Saqueadora",
        value: 100,
        addCart: "Adicionar ao carrinho",
        tag: ["Valorant"],
    },
    {
        id: 3,
        img: "https://valorantskins.com/img/skins/vandal/prime-vandal-skin.png",
        nameItem: "Vandal Sublime",
        value: 100,
        addCart: "Adicionar ao carrinho",
        tag: ["Valorant"],
    },
    {
      id: 4,
      img: "https://valorantskins.com/img/skins/vandal/luxe-vandal-level-4-skin.png",
      nameItem: "Vandal Avalanche",
      value: 100,
      addCart: "Adicionar ao carrinho",
      tag: ["Valorant"],
    },
    {
        id: 5,
        img: "https://gta5mod.net/wp-content/uploads/2022/04/Oni-Phantom-All-Variants4.png",
        nameItem: "Phantom Oni",
        value: 100,
        addCart: "Adicionar ao carrinho",
        tag: ["Valorant"],
    },
    {
        id: 6,
        img: "https://vgraphs.com/images/weapons/skins/full-details/valorant-infinity-phantom-variant-1-white-weapon-skin.png",
        nameItem: "Phantom Rush",
        value: 100,
        addCart: "Adicionar ao carrinho",
        tag: ["Valorant"],
    },
    {
        id: 7,
        img: "https://vgraphs.com/images/weapons/skins/full-details/valorant-singularity-ares-variant-2-red-weapon-skin.png",
        nameItem: "Phantom Singularidade",
        value: 100,
        addCart: "Adicionar ao carrinho",
        tag: ["Valorant"],
    },
    {
        id: 8,
        img: "https://gta5mod.net/wp-content/uploads/2022/04/Oni-Phantom-All-Variants4.png",
        nameItem: "Phantom Oni",
        value: 64.99,
        addCart: "Adicionar ao carrinho",
        tag: ["Valorant"],
    },
    {
        id: 9,
        img: "https://valorantskins.com/img/skins/vandal/prime-vandal-skin.png",
        nameItem: "Vandal Sublime",
        value: 45.99,
        addCart: "Adicionar ao carrinho",
        tag: ["Valorant"],
    },
    {
        id: 10,
        img: "https://valorantskins.com/img/skins/vandal/aristocrat-vandal-skin.png",
        nameItem: "Vandal Aristocrata",
        value: 150.99,
        addCart: "Adicionar ao carrinho",
        tag: ["Valorant"],
    },
    {
        id: 11,
        img: "https://valorantskins.com/img/skins/vandal/luxe-vandal-level-4-skin.png",
        nameItem: "Vandal Avalanche",
        value: 55.99,
        addCart: "Adicionar ao carrinho",
        tag: ["Valorant"],
    },
    {
        id: 12,
        img: "https://vgraphs.com/images/weapons/skins/full-details/valorant-singularity-ares-variant-2-red-weapon-skin.png",
        nameItem: "Phantom Singularidade",
        value: 70.50,
        addCart: "Adicionar ao carrinho",
        tag: ["Valorant"],
    },
]